version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_desafio
    environment:
      POSTGRES_USER: coti
      POSTGRES_PASSWORD: coti
      POSTGRES_DB: controle_gastos
    ports:
      - "5051:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_desafio
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: coti
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: